on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'canary*'

name: Create Canary Release

jobs:
  build:
    name: Create Canary Release
    runs-on: ubuntu-20.04
    container:
        image: prosty/gb300-multicore-builder:v1.1-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build the release
        run: ./.github/scripts/entrypoint.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /__w/gb300_multicore/gb300_multicore/gb300-multicore-canary.tar.gz
          asset_name: gb300-multicore-${{ github.ref }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: |
              Canary (unstable) build of GB300 multicore. It contains latest, untested, changes to the emulation cores.
              Please only use this release prior to backing up your SD card. Kindly report bugs @ our discord server. 